edge center
margin_top    0
margin_left   0
margin_right  0
margin_bottom 44
hide_on_focus_loss no
focus_policy on-demand
start_as_hidden no
background_opacity 0.95
app_id dock
kitty_override window_border_width 2px
kitty_override active_border_color #FF0000
kitty_override window_padding_width 2
